/*  ============================================================================
     TABLE DWH.UTL_CFG initialization/configuration
 ============================================================================ */

 
delete from DWH.UTL_CFG ;
-- Svecchiamento: tengo 30 giorni
INSERT INTO DWH.UTL_CFG (PAR,VAL_NUM,VAL_DATE,VAL_STR, DESCR) VALUES ('AGING_LOG_DUR_DAYS',30,NULL,NULL,'num days to mantain into UTL_LOG (plus other AGING_LOG_FREQ_DAYS days) ');  

-- Test Svecchiamento ogni 7 giorni (tengo quindi da 30 a 37 days), ma risparmio in efficienza (faccio svecchiamnento ogni 7 giorni e non 1 volta al giorno)
INSERT INTO DWH.UTL_CFG (PAR,VAL_NUM,VAL_DATE,VAL_STR, DESCR) VALUES ('AGING_LOG_FREQ_DAYS',7,NULL,NULL,'Frequence (days) of UTL_LOG aging');  
--
INSERT INTO DWH.UTL_CFG (PAR,VAL_NUM,VAL_DATE,VAL_STR, DESCR) VALUES ('AGING_LOG_LAST_DATE',NULL,(SYSDATE - 100),NULL,'Last Aging Date');  
INSERT INTO DWH.UTL_CFG (PAR,VAL_NUM,VAL_DATE,VAL_STR, DESCR) VALUES ('LOG_STATUS_GROUP_ID',1,NULL,NULL,'Current value of UTL_LOG_STATUS.GROUP_ID');  


-- Usati solo per testare lo svecchiamento
INSERT INTO DWH.UTL_LOG VALUES ('TEST','SP_TST',1,TO_TIMESTAMP(SYSDATE-5), NULL, NULL, NULL);
INSERT INTO DWH.UTL_LOG VALUES ('TEST','SP_TST',1,TO_TIMESTAMP(SYSDATE-4), NULL, NULL, NULL);
INSERT INTO DWH.UTL_LOG VALUES ('TEST','SP_TST',1,TO_TIMESTAMP(SYSDATE-3), NULL, NULL, NULL);
INSERT INTO DWH.UTL_LOG VALUES ('TEST','SP_TST',1,TO_TIMESTAMP(SYSDATE-2), NULL, NULL, NULL);
INSERT INTO DWH.UTL_LOG VALUES ('TEST','SP_TST',1,TO_TIMESTAMP(SYSDATE-1), NULL, NULL, NULL);

INSERT INTO DWH.UTL_LOG_STATUS VALUES (0,20180401,'TEST','TEST_SP',TO_TIMESTAMP(SYSDATE-5), NULL, 0, 'TEST',NULL,NULL);
INSERT INTO DWH.UTL_LOG_STATUS VALUES (0,20180402,'TEST','TEST_SP',TO_TIMESTAMP(SYSDATE-4), NULL, 0, 'TEST',NULL,NULL);
INSERT INTO DWH.UTL_LOG_STATUS VALUES (0,20180403,'TEST','TEST_SP',TO_TIMESTAMP(SYSDATE-3), NULL, 0, 'TEST',NULL,NULL);
INSERT INTO DWH.UTL_LOG_STATUS VALUES (0,20180404,'TEST','TEST_SP',TO_TIMESTAMP(SYSDATE-2), NULL, 0, 'TEST',NULL,NULL);
INSERT INTO DWH.UTL_LOG_STATUS VALUES (0,20180405,'TEST','TEST_SP',TO_TIMESTAMP(SYSDATE-1), NULL, 0, 'TEST',NULL,NULL);



COMMIT;


